var express = require('express');
var router = express.Router();

const nameList = [
  {'Id': 1,'Term':'DevOps','Description':'  is a set of practices, tools, and a cultural philosophy that automate and integrate the processes between software development and IT teams. It emphasizes team empowerment, cross-team communication and collaboration, and technology automation','reference':'I. Sommerville et al., “SOFTWARE ENGINEERING Ninth Edition.” Available: https://www.atlassian.com/devops</'},
  {'Id': 2,'Term':'The Wall of Confusion','Description':'It refers to the phenomena where one group in a value stream approaches their job as complete when they have passed it onto the next group','reference':'I. Sommerville et al., “SOFTWARE ENGINEERING Ninth Edition.” Available: https://levelup.gitconnected.com/the-wall-of-confusion-623057a4dd26/'},
  {'Id': 3, 'Term':"UX",'Description':'UX design is the design of the elements that determine the interaction a user has with a product or service.','reference':'https://careerfoundry.com/en/blog/ux-design/what-is-user-experience-ux-design-everything-you-need-to-know-to-get-started/'},
  {'Id': 4, 'Term':"Continuous Integration (CI)",'Description':'Continuous Integration (CI) is a software development practice that aims to streamline the process of building, testing, and integrating code changes into a shared repository. By automating these tasks, CI allows developers to frequently and efficiently integrate their changes, often multiple times a day.','reference':'S. Hamdan and S. Alramouni, “A Quality Framework for Software Continuous Integration,” Procedia Manufacturing, vol. 3, pp. 2019–2025, 2015, doi: https://doi.org/10.1016/j.promfg.2015.07.249'},
  {'Id': 5, 'Term':"Nodejs",'Description':'Is an open-source and cross-platform JavaScript runtime environment. It is a popular tool for almost any kind of project! ','reference':'Kim, Gene, et al. "Accelerate: The Science of Lean Software and DevOps: Building and Scaling High Performing Technology Organizations." IT Revolution Press, 2018.'},
  {'Id': 6, 'Term':"Software Change Management",'Description':'The term Software Change Management refers to a structured and systematic approach that organizations use to plan, implement, and manage changes in a controlled manner.','reference':'A. A. Khan, S. Basri, and P. D. D. Dominic, “A propose framework for requirement Change Management in Global Software Development,” 2012 International Conference on Computer & Information Science (ICCIS), Jun. 2012, doi: https://doi.org/10.1109/iccisci.2012.6297161.'},
  {'Id': 7, 'Term':"Release Management",'Description':'The process involves the planning, development, testing, deployment, and monitoring of a software release.','reference':'A. van der Hoek, R. S. Hall, D. Heimbigner, and A. L. Wolf, “Software release management,” ACM SIGSOFT Software Engineering Notes, vol. 22, no. 6, pp. 159–175, Nov. 1997, doi: https://doi.org/10.1145/267896.267909.'},
  {'Id': 8, 'Term':"Downtime",'Description':'A downtime occurs when a piece of software is not available for users to use. It is the opposite of an uptime, which is a period during which the software is running.','reference':'D. Patterson, “A Simple Way to Estimate the Cost of Downtime,” 2002. Accessed: Jul. 23, 2023. [Online]. Available: http://roc.cs.berkeley.edu/papers/Cost_Downtime_LISA.pdf'},
  {'Id': 9, 'Term':"Monitoring and Alerting",'Description':'Monitoring and alerting are critical components of software operations and infrastructure management. A software performance monitor is employed to ensure that software systems perform well, are available, and reliable, as well as to detect and respond to any anomalies that may occur. Alerting is the process of setting up rules and thresholds based on predefined conditions or criteria in the monitored data. When these conditions are met or when anomalies are detected, the monitoring system generates alerts or notifications to notify the responsible teams about potential issues.','reference':'"The DevOps Handbook: How to Create World-Class Agility, Reliability, and Security in Technology Organizations" by Gene Kim, Patrick Debois, John Willis, and Jez Humble. This book covers various aspects of DevOps, including monitoring, alerting, and improving IT operations.'},
  {'Id':10, 'Term':"Devops",'Description':'DevOps is a set of practices and cultural philosophies aimed at improving collaboration and communication between development teams (Dev) and IT operations teams (Ops). The goal is to break down the traditional silos between these teams and encourage a culture of shared ownership across the software development and delivery lifecycle','reference':'C. Ebert, G. Gallardo, J. Hernantes, and N. Serrano, “DevOps,” IEEE Software, vol. 33, no. 3, pp. 94–100, May 2016, doi: https://doi.org/10.1109/ms.2016.68. “(PDF) A Qualitative Study of DevOps Usage in Practice,” ResearchGate. https://www.researchgate.net/publication/316879884_A_Qualitative_Study_of_DevOps_Usage_in_Practic'},
  {'Id':11, 'Term':'Automation', 'Description': 'automation refers to the practice of using technology, scripts, tools, and processes to automate various tasks and workflows throughout the software development and delivery lifecycle.', 'reference':'D. Sato, Devops in Practice. Editora Casa do Código, 2014.'},
  {'Id':12, 'Term':'Agile', 'Description': 'Agile is a software development which aims to deliver valuable software to users more frequently and effectively by breaking down projects into smaller, manageable units of work called "sprints" or "iterations." ', 'reference':'Orit Hazzan and Y. Dubinsky, Agile software engineering. London: Springer, 2008.'},
  {'Id':13, 'Term':'Scrum', 'Description': 'Scrum is an agile project management framework that helps teams structure and manage their work through a set of values, principles, and practice.','reference':' atlassian .(n.d). A Beginner’s Guide to Scrum . Available at: https://www.atlassian.com/agile/scrum'},
  {'Id':14, 'Term':'CI/CD tools', 'Description': 'The best platform for cross-functional work, easy to organize and deliver quality work, faster.','reference':' Asana. (2023). https://asana.com.'},
  {'Id':15, 'Term':'npm run', 'Description': 'The npm run command is used in Node.js and npm (Node Package Manager) to execute scripts defined in a projects package.json file. The npm run command is especially useful for automating common development tasks such as starting a development server, building production assets, running tests, and more. ', 'reference':'A. Patel, Hands-On Full-Stack Development with Swift : Develop full-stack web and native mobile applications using Swift and Vapor. Birmingham: Packt Publishing, 2018. '},
  {'Id':16, 'Term':'Micro services', 'Description': 'Microservices is an architectural style in software development where a complex application is broken down into a set of smaller, loosely coupled, and independently deployable services. Each of these services represents a specific functionality or feature of the application', 'reference':'Irakli Nadareishvili, R. Mitra, M. McLarty, and M. Amundsen, Microservice Architecture. “O’Reilly Media, Inc.,” 2016.'},
  {'Id':17, 'Term':'Docker', 'Description': 'Docker is a platform that enables developers to develop, ship, and run applications in containers. Containers are lightweight and portable environments that package together an applications code, runtime, libraries, and dependencies, allowing it to run consistently across different computing environments', 'reference':'Pethuru Raj, Learning Docker. 2017.'},
  {'Id':18, 'Term':'Asana', 'Description': 'Open source projects make their source code available to the public, allowing anyone to view, modify, and distribute the code according to the terms of the projects license.', 'reference':'ibrary And Information Technology Association (É.-U, Open source software for libraries : an open source for libraries collaboration. Chicago: Lita, 2002.'},
  {'Id':19, 'Term':'IntelliJ IDEA', 'Description': 'The IDE that makes development a more productive and enjoyable experience.','reference':' IntelliJ IDEA (2023). Available at: https://www.jetbrains.com/idea'},
  {'Id':20, 'Term':'DBMS', 'Description': 'DBMS stands for "Database Management System." Its a software system designed to manage, store, retrieve, and manipulate data in a structured and organized way. A DBMS provides an interface for users and applications to interact with databases, ensuring data integrity, security, and efficient data management.', 'reference':'B. L. Larson, SQL solutions for IBM DBMS. New York: Vnr Van Nostrand Reinhold, 1991.'}, 
  {'Id': 21, 'Term':'Docker','Description':'Docker is a PaaS product that uses OS-level virtualization to deliver software in containers, with free and premium tiers. Docker Engine hosts containers, automating application deployment in lightweight containers for efficient isolation.','reference':'Docker, “Docker overview,” Docker Documentation, Apr. 09, 2020. https://docs.docker.com/get-started/overview/'},
  {'Id': 22, 'Term':'Docker Compose','Description':'Compose is a Docker tool that defines and runs multi-container applications using a YAML file, managing application lifecycle, service status, and variables across various environments.','reference':'Docker, “Overview of Docker Compose,” Docker Documentation, Feb. 10, 2020. https://docs.docker.com/compose/'},
  {'Id': 23, 'Term':'Image','Description':'Docker images are files used to execute code in a Docker container, acting as instructions and starting points. They have multiple layers, speeding up builds, increasing reusability, and decreasing disk use. Once created, a writable layer allows user changes.','reference':'What is a Docker Image? Introduction and use cases,” SearchITOperations. https://www.techtarget.com/searchitoperations/definition/Docker-image'},
  {'Id': 24, 'Term':'Dockerfile','Description':'Building a Docker image is explained in detail in a text file, along with how to install dependencies, set up the environment, and make additional configurations.','reference':'Docker Documentation, Sep. 08, 2019. https://docs.docker.com/engine/reference/builder/'},
  {'Id': 25, 'Term':'Container','Description':'A container is a runnable image instance, accessible via the Docker API or CLI, defined by its image and configuration options, and its state changes upon removal.','reference':'Docker overview,” Docker Documentation, Sep. 10, 2023. https://docs.docker.com/get-started/overview/#containers (accessed Aug. 23, 2023).'},
  {'Id': 26, 'Term':'Registry','Description':'An archive for distributing and keeping Docker images. A well-known public registry is Docker Hub, and secure image storage can also be achieved through the creation of private registries.','reference':'Docker Registry,” Docker Documentation, Apr. 23, 2021. https://docs.docker.com/registry/'},
  {'Id': 27, 'Term':'Repository','Description':'Docker Registry is a server-side application that stores and manages Docker images, serving as a central hub for sharing and distributing them, particularly Docker Hub','reference':'Create repositories,” Docker Documentation, Aug. 22, 2023. https://docs.docker.com/docker-hub/repos/create/ (accessed Aug. 23, 2023).'},
  {'Id': 28, 'Term':'Docker build','Description':'The docker build command generates a Docker image from a specified Dockerfile, with options like -t, build-arg, or -f, and a build context specified by PATH | URL.','reference':'S. James, “Docker Build: A Beginner’s Guide to Building Docker Images,” Stackify, Jul. 12, 2019. https://stackify.com/docker-build-a-beginners-guide-to-building-docker-images/'},
  {'Id': 29, 'Term':'Docker Run','Description':'The docker run command creates a new container from a Docker image, allowing configuration and management options like detaching, publishing, name, environment variables, volume mount, network connection, and interactive session start.','reference':'S. James, “Docker Build: A Beginner’s Guide to Building Docker Images,” Stackify, Jul. 12, 2019. https://stackify.com/docker-build-a-beginners-guide-to-building-docker-images/'},
  {'Id': 30, 'Term':"Source Control",'Description':'Source control is a software development system that tracks changes to files and folders, enabling collaboration, code management, conflict resolution, and backup. Common systems like Git, SVN, and Mercurial provide efficient collaboration, code management, and improved software quality.','reference':'F. Santacroce author., A. Olsson, R. Voss, and J. Narębski, Git : mastering version control. Packt Publishing, 2016. Accessed: Aug. 06, 2023. [Online]. Available: https://eds.p.ebscohost.com/eds/detail/detail?vid=0&sid=a00e23bc-ed8d-4b92-b41f-9ed87c505ee1%40redis&bdata=JnNpdGU9ZWRzLWxpdmUmc2NvcGU9c2l0ZQ%3d%3d#AN=deakin.b3649851&db=cat00097a'},
  {'Id': 31, 'Term':'Kubernetes','Description':'Kubernetes, also known as K8s, is an open-source system for automating deployment, scaling, and management of containerized applications.','reference':'Docker, “Kubernetes,”  Documentation, https://kubernetes.io//'},
  {'Id': 32, 'Term':'Open Shift','Description':'Red Hat OpenShift is a strong alternative solution and Kubernetes-based platform that enhances Kubernetes with several new capabilities made specifically for enterprise use.','reference':'OpenShift, “Red Hat OpenShift,”  2023. https://www.redhat.com/en/technologies/cloud-computing/openshift'},
  {'Id': 33, 'Term':'Managing Storage','Description':'Managing storage is a distinct problem from managing compute instances. The PersistentVolume subsystem provides an API for users and administrators that abstracts details of how storage is provided from how it is consumed.','reference':'Persistent Volumes,” . https://kubernetes.io/docs/concepts/storage/persistent-volumes/'},
  {'Id': 34, 'Term':'Pod','Description':'Smallest deployable unit in Kubernetes, containing one or more containers.','reference':'. https://kubernetes.io/docs/concepts/workloads/pods/'},
  {'Id': 35, 'Term':'Node','Description':'Individual physical or virtual machine in a Kubernetes cluster.','reference':'Kubernetes overview,” Kubernetes Official Documentation,. https://kubernetes.io/docs/concepts/architecture/nodes/'},
  {'Id': 36, 'Term':'Ingress','Description':'  Kubernetes resource for managing external access to services.','reference':'Ingress,” Kubernetes Official Documentation. https://kubernetes.io/docs/concepts/services-networking/ingress/'},
  {'Id': 37, 'Term':'Kubectl','Description':'Command-line tool for interacting with Kubernetes clusters.','reference':'Kubectl, kubernetes Documentation, . https://kubernetes.io/docs/reference/kubectl/ (accessed Aug. 23, 2023).'},
  {'Id': 38, 'Term':'Plan','Description':' Preview of changes Terraform will apply to infrastructure.','reference':'Terraform Official Documentation,. https://developer.hashicorp.com/terraform/cli/commands/plan'},
  {'Id': 39, 'Term':'Module','Description':'Reusable unit of Terraform configuration for managing related resources.','reference':' Terraform Official Documentation https://developer.hashicorp.com/terraform/language/modules'},
  {'Id': 40, 'Term':"Source Control",'Description':' Infrastructure component managed by Terraform (e.g., VM, database).','reference':' Terraform Official Documentation. Accessed: Sep. 09, 2023. [Online]. Available:https://developer.hashicorp.com/terraform/language/resources'}
  
];

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 Devops Glossary', sub:'Welcome to mywebsite showing a collection of Devops terms and their brief description', names:nameList});
});

module.exports = router;